### ISSUE TITLE
Minecraft Crash: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2874.method_27999()'

### ISSUE THREAD

**Issue by lospejos** [MSandro/clay-bucket#1]
I have `Minecraft 1.19` with `Quilt` (and `Quilted Fabric`) mod loader:

Mods and versions:

    qfapi-2.0.0-beta.1_qsl-2.0.0-beta.8_fapi-0.56.3_mc-1.19.jar
    claybucket-1.0.1a.jar

When I try to place fluid (water) from `Water Clay Bucket` into Hopper, Minecraft crashes:

```
Time: 6/26/22, 10:35 AM
Description: Unexpected error

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2874.method_27999()'
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at com.msandro.claybucket.ClayBucketItem.placeFluid(ClayBucketItem.java:173)
	at com.msandro.claybucket.ClayBucketItem.use(ClayBucketItem.java:101)
	at net.minecraft.item.ItemStack.use(ItemStack:276)
	at net.minecraft.client.network.ClientPlayerInteractionManager.method_41929(ClientPlayerInteractionManager:387)
	at net.minecraft.client.network.ClientPlayerInteractionManager.sendSequencedPacket(ClientPlayerInteractionManager:278)
	at net.minecraft.client.network.ClientPlayerInteractionManager.interactItem(ClientPlayerInteractionManager:379)
	at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient:1731)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1964)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1791)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.msandro.claybucket.ClayBucketItem.method_7731(ClayBucketItem.java:173)
	at com.msandro.claybucket.ClayBucketItem.method_7836(ClayBucketItem.java:101)
	at net.minecraft.class_1799.method_7913(class_1799.java:276)
	at net.minecraft.class_636.method_41929(class_636.java:387)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2919(class_636.java:379)
	at net.minecraft.class_310.method_1583(class_310.java:1731)
	at net.minecraft.class_310.method_1508(class_310.java:1964)

-- Affected level --
Details:
	All players: 1 total; [class_746['a'/207, l='ClientLevel', x=-554.30, y=61.50, z=-68.75]]
	Chunk stats: 1024, 621
	Level dimension: minecraft:overworld
	Level spawn location: World: (-560,67,-48), Section: (at 0,3,0 in -35,4,-3; chunk contains blocks -560,-64,-48 to -545,319,-33), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 64969 game time, 64969 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
```
I also tried to put water from vanilla `Iron Bucket` into the same hopper, and it was succeeded.

I'm not sure is it a `Clay Bucket` mod issue or another mod issue or it's a kind of a mod incompatibility.
I also suppose (but I'm not sure) that this may be an issue related to `Quilt/Quilted Fabric` versions (Quilt is in beta AFAIK).
Please assist if you can. thanks.

**Comment by lospejos** [comment]
Also this exception appears when putting water out from `Clay Water Bucket` not only into hopper, but simply on earth.

**Comment by FoggyWizard** [comment]
Can confirm. Same error just trying to place water.

**Comment by lospejos** [comment]
It seems this repo is not supported anymore.
For the benefit of others. I've found an alternative: 

https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket

**Comment by FoggyWizard** [comment]
Mate did you really just present a forge mod as an alternative to a fabric one? Because that's not going to help anyone who is using a fabric modlist who wants an early game bucket. It's apples to oranges, even if they both have the same general function.
